"use client";
import { motion, useInView } from "motion/react";
import { useRef, useState } from "react";
import { scenarios } from "@/lib/constants/scenarios";
import { Phone } from "@/components/phone/Phone";
import { Reveal } from "@/components/ui/Reveal";
export function ScenarioShowcase(){return <section className="scenario-showcase"><div className="section-intro"><span className="eyebrow">THREAD IN ACTION</span><h2>Things your phone should <em>just know.</em></h2></div>{scenarios.map((scene,i)=><Scene key={scene.mode} {...scene} flip={i%2===1}/>)}</section>}
function Scene({number,title,italic,copy,mode,flip}:{number:string;title:string;italic:string;copy:string;mode:"reminder"|"ticket"|"office";flip:boolean}){const ref=useRef<HTMLElement>(null);const inView=useInView(ref,{once:true,margin:"-20%"});return <article ref={ref} className={`scenario ${flip?"flip":""}`}><Reveal><div className="scene-copy"><span>{number}</span><h3>{title}<br/><em>{italic}</em></h3><p>{copy}</p></div></Reveal><motion.div initial={{opacity:0,y:50,rotate:flip?4:-4}} animate={inView?{opacity:1,y:0,rotate:0}:{}} transition={{type:"spring",stiffness:90,damping:18}}><Phone mode={mode}/></motion.div></article>}
export function NeedleSection(){const ref=useRef<HTMLElement>(null);const visible=useInView(ref,{once:true,margin:"-15%"});const steps=["OTHER FOSS MODELS|STT · OCR · embeddings · retrieval|What is happening?","NEEDLE 2|intent → tool retrieval → structured call → confidence|What should the phone do?","TOOLS|Android APIs · Files · Calendar · Office Kit|Actually do it."];return <section ref={ref} className="needle-section"><Reveal><span className="eyebrow">THE TECHNICAL SHOWCASE</span><h2>Needle 2.</h2><h3>The <em>action layer.</em></h3><p>A lightweight on-device model built for tool calling, not conversation.</p></Reveal><div className="pipeline">{steps.map((step,i)=>{const [title,body,caption]=step.split("|");return <motion.div key={title} initial={{opacity:0,y:25}} animate={visible?{opacity:1,y:0}:{}} transition={{delay:.2+i*.22,duration:.6}} className="pipeline-step"><b>{title}</b><span>{body}</span><small>“{caption}”</small>{i<2&&<i>↓</i>}</motion.div>})}</div><div className="spec-grid">{["~45M|parameters","~14 MB|binary","~28 MB|session RAM","ARM64|Android native","STRUCTURED|tool calls","CONFIDENCE|aware execution"].map(v=>{const[a,b]=v.split("|");return <div key={a}><b>{a}</b><span>{b}</span></div>})}</div><div className="footprint">{[["NEEDLE 2","45M",8],["SMALL LOCAL LLM","1B+",45],["LARGER LOCAL LLM","3B+",100]].map(([name,value,width])=><div key={String(name)}><span>{name}</span><i><motion.b initial={{scaleX:0}} animate={visible?{scaleX:1}:{}} transition={{duration:.8}} style={{width:`${width}%`}}/></i><small>{value}</small></div>)}<p>ILLUSTRATIVE PARAMETER-COUNT COMPARISON · FOOTPRINT ONLY — NOT A PERFORMANCE CLAIM</p></div></section>}
export function Confidence(){const [mode,setMode]=useState<"high"|"medium"|"low">("high");const values={high:["I found the PDF Rahul meant.","iQOO_Hackathon_Guide.pdf","SEND"],medium:["I found 2 possible PDFs.","Choose the one Rahul meant.","CHOOSE"],low:["I couldn't confidently identify the file.","Try a search instead.","SEARCH"]};return <section className="confidence-section"><Reveal><span className="eyebrow">CONFIDENCE / TRUST</span><h2>Not every context deserves an action.</h2></Reveal><div className="confidence-layout"><div className="confidence-buttons">{(["high","medium","low"] as const).map(m=><button onClick={()=>setMode(m)} className={mode===m?"active":""} key={m}>{m.toUpperCase()} <span>→ {m==="high"?"ACT":m==="medium"?"ASK":"DON'T"}</span></button>)}</div><motion.div layout><Phone stage={4}/><motion.div className="confidence-overlay" key={mode} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><span>THREAD</span><b>{values[mode][0]}</b><small>{values[mode][1]}</small><button>{values[mode][2]}</button></motion.div></motion.div></div><p className="trust-note">PERMISSION-AWARE · ON-DEVICE · USER REMAINS IN CONTROL</p></section>}
